import random

# Get a random number from 0 to 100
rand_number = random.randint(0,101)

def guessingGame(player_guessed_numb:int, tries_left: int, number_tries:int):
    """
    The guessing game: Player try to guess the number randomly generated by the computer

    Input Parameter
    ***************
    player_guessed_numb: An integer number from 0 to 100

    Output
    ******
    The game indicate if you guessed right or wrong
    """
 
    if player_guessed_numb == rand_number:
        print("\nYou guessed Right")
        print(f"It took you {number_tries} guesses")
    elif player_guessed_numb > rand_number:
        print("\nYou guessed too high")
        print("Try again!!!")
        print(f"You have {tries_left} tries left")
    elif player_guessed_numb < rand_number:
        print("\nYou guessed too low")
        print("Try again!!!")
        print(f"You have {tries_left} tries left")


#Get guessed number from player
max_tries = 10
tries_leftn = 10
number_triesn=0

for i in range(max_tries):
    player_number = int(input("\nPlease guess a number between 0 to 100 : "))
    tries_leftn = tries_leftn - 1
    number_triesn = i+1
    guessingGame(player_number,tries_leftn,number_triesn)

    if player_number == rand_number:
        break
else:
    print("\nYou have reached your maximum tries (10 tries)\nGame Over!!!")




